main: Main.main
version: 1.0
name: NonelessGame

commands:
  CreateArena:
    description: Erstelle eine Arena
  TestSummon:
    description: Testet die Arena
  Duell:
    description: Startet ein duell
  nextPhase:
    description: Startet ein duell